server.port=8080

spring.data.mongodb.uri=${SPRING_MONGODB_URI}

spring.data.redis.host=${REDIS_HOST}
spring.data.redis.port=${REDIS_PORT}

spring.kafka.bootstrap-servers=${KAFKA_SERVERS}

inventory.service.url=${INVENTORY_SERVICE_URL}

management.endpoints.web.exposure.include=health,info,prometheus
management.endpoint.prometheus.access=unrestricted