spring.application.name=main

server.port=8080

spring.data.mongodb.uri=mongodb://localhost:27017/ecommerce

spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.data.redis.repositories.enabled=false
spring.cache.type=redis

spring.datasource.url=jdbc:postgresql://localhost:5432/inventory_db
spring.datasource.username=postgres
spring.datasource.password=password
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true

spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.group-id=ecommerce-group

app.kafka.topics.order-created=order-created
app.kafka.topics.order-cancelled=order-cancelled
app.kafka.topics.order-updated=order-updated
app.kafka.topics.inventory-reserved=inventory-reserved
app.kafka.topics.inventory-restored=inventory-restored
app.kafka.topics.inventory-failed=inventory-failed
app.kafka.topics.inventory-updated=inventory-updated

inventory.service.url=http://localhost:8080/inventory
