name: PR Checks

on:
  pull_request:
  workflow_dispatch:

jobs:

  frontend-lint-and-test:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: frontend

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Run ESLint
        run: npm run lint

      - name: Run frontend tests
        run: npm run test -- --run


  backend-check:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_DB: inventory_db
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          cache: maven

      - name: Make mvnw executable
        run: chmod +x backend/mvnw

      - name: Run backend tests (all modules)
        working-directory: backend
        env:
          SPRING_DATASOURCE_URL: jdbc:postgresql://localhost:5432/inventory_db
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
        run: ./mvnw clean test

      - name: Run Checkstyle
        working-directory: backend
        run: ./mvnw checkstyle:check